# Generated by Django 3.2.5 on 2022-02-10 14:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('db_status', models.IntegerField(choices=[(-1, 'Deleted'), (0, 'Pending'), (1, 'Active')], default=1)),
                ('name', models.CharField(max_length=200)),
                ('id_string', models.CharField(max_length=200)),
                ('chain_id', models.CharField(default='bsc_mainnet', max_length=50)),
                ('address', models.CharField(max_length=42)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(default='ERC20', max_length=20)),
                ('symbol', models.CharField(max_length=50)),
                ('total_supply', models.FloatField(default=0)),
                ('decimals', models.IntegerField(default=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('db_status', models.IntegerField(choices=[(-1, 'Deleted'), (0, 'Pending'), (1, 'Active')], default=1)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('item_id', models.CharField(max_length=128)),
                ('current_price', models.FloatField(default=0)),
                ('media_url', models.CharField(blank=True, max_length=512, null=True)),
                ('last_time_log', models.DateTimeField(default=datetime.datetime.now)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to='governance.tokencontract')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
