# Generated by Django 3.2.5 on 2022-02-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='validation_score',
            new_name='score_validation',
        ),
        migrations.RenameField(
            model_name='contribute',
            old_name='validation_score',
            new_name='score_validation',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='validation_score',
            new_name='score_validation',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='validation_score',
            new_name='score_validation',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='current_price',
            new_name='price_current',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='init_price',
            new_name='price_init',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='validation_score',
            new_name='score_validation',
        ),
        migrations.AddField(
            model_name='project',
            name='launch_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='score_hunt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='price_ath',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='price_atl',
            field=models.FloatField(default=0),
        ),
    ]
