# Generated by Django 3.2.5 on 2022-02-24 08:21

import apps.project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20220223_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='partners',
            field=models.JSONField(blank=True, default=apps.project.models.default_partners, null=True),
        ),
    ]
