# Generated by Django 3.2.5 on 2022-02-25 08:05

import apps.project.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_check', models.DateTimeField(default=django.utils.timezone.now)),
                ('social_metric', models.CharField(max_length=50)),
                ('social_id', models.CharField(max_length=50)),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='options',
            field=models.JSONField(blank=True, default=apps.project.models.default_options, null=True),
        ),
        migrations.AddField(
            model_name='tokenprice',
            name='volume',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='TokenLog',
        ),
    ]
