# Generated by Django 3.2.5 on 2022-02-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20220225_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='socials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
