# Generated by Django 3.2.5 on 2022-04-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20220402_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_end_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_end_h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_end_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_end_mo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_end_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_start_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_start_h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_start_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_start_mo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_start_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenprice',
            name='range',
            field=models.CharField(db_index=True, default='m5', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='targets',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='target_events', to='project.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='launch_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='term',
            name='id_string',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='token',
            name='address',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
