# Generated by Django 3.2.5 on 2022-04-11 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20220411_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialtracker',
            name='time_check',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
