# Generated by Django 3.2.5 on 2022-02-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
