# Generated by Django 3.2.5 on 2022-02-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='chain',
            field=models.CharField(default='binance-smart-chain', max_length=20),
        ),
    ]
